import { IColumn } from '@skatteetaten/frontend-components/DetailsList/DetailsList.types';
import { sort } from 'web/components/DetailsListUtils/column/sortUtils';

export const azureColumns: IColumn[] = [
  {
    name: 'Name',
    fieldName: 'name',
    isResizable: true,
    key: '0',
    maxWidth: 420,
    minWidth: 420,
    sortItems: sort,
    isMultiline: true,
  },
  {
    name: 'CName',
    fieldName: 'canonicalName',
    isResizable: true,
    key: '1',
    maxWidth: 200,
    minWidth: 200,
    sortItems: sort,
    isMultiline: true,
  },
  {
    name: 'TTL',
    fieldName: 'ttlInSeconds',
    isResizable: true,
    key: '2',
    maxWidth: 50,
    minWidth: 50,
    sortItems: sort,
  },
  {
    name: 'Namespace',
    fieldName: 'namespace',
    isResizable: true,
    key: '3',
    maxWidth: 200,
    minWidth: 200,
    sortItems: sort,
    isMultiline: true,
  },
  {
    name: 'Applikasjon',
    fieldName: 'ownerObjectName',
    isResizable: true,
    key: '4',
    maxWidth: 200,
    minWidth: 200,
    sortItems: sort,
    isMultiline: true,
  },
];

export const onpremColumns: IColumn[] = [
  {
    name: 'Status',
    fieldName: 'status',
    isResizable: true,
    key: '0',
    maxWidth: 160,
    minWidth: 160,
    sortItems: sort,
    isMultiline: true,
  },
  {
    name: 'CName',
    fieldName: 'cname',
    isResizable: true,
    key: '1',
    maxWidth: 420,
    minWidth: 420,
    sortItems: sort,
    isMultiline: true,
  },
  {
    name: 'TTL',
    fieldName: 'ttl',
    isResizable: true,
    key: '2',
    maxWidth: 50,
    minWidth: 50,
    sortItems: sort,
  },
  {
    name: 'Namespace',
    fieldName: 'namespace',
    isResizable: true,
    key: '3',
    maxWidth: 130,
    minWidth: 130,
    sortItems: sort,
    isMultiline: true,
  },
  {
    name: 'Applikasjon',
    fieldName: 'appName',
    isResizable: true,
    key: '4',
    maxWidth: 250,
    minWidth: 250,
    sortItems: sort,
    isMultiline: true,
  },
  {
    name: 'Rute',
    fieldName: 'routeName',
    isResizable: true,
    key: '5',
    maxWidth: 280,
    minWidth: 280,
    sortItems: sort,
    isMultiline: true,
  },
  {
    name: 'Meldinger',
    fieldName: 'message',
    isResizable: true,
    key: '6',
    maxWidth: 100,
    minWidth: 100,
    sortItems: sort,
    isMultiline: true,
  },
];
