export const FETCHED_SCHEMA_REQUEST = 'database/FETCHED_SCHEMA_REQUEST';
export const FETCHED_SCHEMA_SUCCESS = 'database/FETCHED_SCHEMA_SUCCESS';
export const FETCHED_SCHEMA_FAILURE = 'database/FETCHED_SCHEMA_FAILURE';
