export enum ImageTagType {
  AURORA_VERSION = 'AURORA_VERSION',
  AURORA_SNAPSHOT_VERSION = 'AURORA_SNAPSHOT_VERSION',
  BUGFIX = 'BUGFIX',
  LATEST = 'LATEST',
  MAJOR = 'MAJOR',
  MINOR = 'MINOR',
  SNAPSHOT = 'SNAPSHOT',
  COMMIT_HASH = 'COMMIT_HASH',
  SEARCH = 'SEARCH'
}
